storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
packages:
  "@*/*":
    access: $all
    publish: $all
  "**":
    access: $all
    publish: $all
logs:
  - { type: stdout, format: pretty, level: http }
